apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -preprod
namespace: demo-preprod

resources:
- ../../base

patches:
- path: deployment-patch.yaml

images:
- name: petstore-ref-arch
  newName: 092223502519.dkr.ecr.us-west-2.amazonaws.com/omni-channel-platform
  newTag: ref-arch-585a6707-6820-456a-9e3d-a88dcbf072ba