name: Use Reusable .NET Core CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-reusable-workflow:
    uses: wilson-molano-fernandez/clean-architecture/.github/workflows/use-shared.yml@main
    with:
      environment: 'development'     