name: Use Reusable .NET Core CI Workflow

on:
  push:
    branches:
      - mainy
  pull_request:
    branches:
      - mainy

jobs:
  call-reusable-workflow:
    uses: wilson-molano-fernandez/clean-architecture/.github/workflows/dotnet-ci-workflow.yml@main
    with:
      environment: 'development'     